const colors = {
  light: {
    text: "#111111",
    tint: "#E85D04",
    background: "#F8F8F8",
    foreground: "#111111",
    card: "#FFFFFF",
    cardForeground: "#111111",
    primary: "#E85D04",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F3F3",
    secondaryForeground: "#333333",
    muted: "#F0F0F0",
    mutedForeground: "#6B7280",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#F3F4F6",
  },

  dark: {
    text: "#FFFFFF",
    tint: "#E85D04",
    background: "#0A0A0A",
    foreground: "#FFFFFF",
    card: "#141414",
    cardForeground: "#FFFFFF",
    primary: "#E85D04",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C1C",
    secondaryForeground: "#FFFFFF",
    muted: "#1A1A1A",
    mutedForeground: "#9E9E9E",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1C1C1C",
  },

  radius: 12,
};

export default colors;
